# Generated by Django 3.2.5 on 2021-07-07 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idpais', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de pais')),
                ('nombrepais', models.CharField(max_length=50, verbose_name='Nombre del país')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idproveedor', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de proveedor')),
                ('foto', models.ImageField(null=True, upload_to='Proveedores')),
                ('nombre_completo', models.CharField(max_length=60, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(max_length=12, verbose_name='telefono')),
                ('direccion', models.CharField(max_length=100, verbose_name='telefono')),
                ('email', models.CharField(max_length=60, verbose_name='telefono')),
                ('contrasena', models.CharField(max_length=15, verbose_name='contraseña')),
                ('monedapago', models.CharField(max_length=10, verbose_name='tipo de moneda de pago')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GroundZero.pais')),
            ],
        ),
    ]
