# Generated by Django 3.2.5 on 2021-07-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroundZero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.CharField(max_length=60, verbose_name='email'),
        ),
    ]
